### ISSUE TITLE
No application running with Flow, even though IDE launch was successfull

### ISSUE THREAD

**Issue by Litrico** [findtheflow/Feedback#12]
Hi,

I just updated the plugin within intellij IDEA, but when I launch the app with the flow recording and I get the "Application is running with Flow: Click here to see and record the execution manually" it doesn't show an active application beneath "Executions".

It was working fine before the latest update.

**Comment by yiquanzhou** [comment]
Thank you for reporting the issue. 
Apparently the issue occurs when the recording is not started automatically from the beginning. It's probably a regression in the latest version that we will try to fix as soon as possible. You can revert back to the previous version for the moment.

**Comment by YoannBuch** [comment]
It is fixed now (version 20170531202529), you just need to upgrade the plugin.

It was affecting all users so thanks again for reporting this issue!
