### ISSUE TITLE
Adding the same package to the include and exclude locks the visualiser

### ISSUE THREAD

**Issue by offworldcoder** [findtheflow/Feedback#16]
I added an elready excluded item to the include list (thought it would be easier/quicker than changing the list in intellij and rerun to get my package back).

Visualisation went blank and no longer responds.

**Comment by yiquanzhou** [comment]
In the case where a package is in both include and exclude list, we exclude the only package that is included. So nothing will be displayed. We will add warning to avoid this case. Thanks!

**Comment by yiquanzhou** [comment]
Fixed in v20170718200811
