### ISSUE TITLE
Nice To Have: Apply visualisation filter changes to Intellij Run/Debug configuration

### ISSUE THREAD

**Issue by offworldcoder** [findtheflow/Feedback#18]
It's quite difficult to trim down the visualisation content using the Run/Debug configuration. However it appears that making those filtering change on the visualisation diagram work much better but they get lost once you close the visualisation and/or intellij.

**Comment by yiquanzhou** [comment]
The filters (include, exclude, threads, visibilities) are saved in the url of the recording except the time window zoom. So you can eventually save the url and reopen it later and all these filters will re-apply automatically to the recording. It can be useful to share the recording with someone.
Is this helpful to your use case?

**Comment by offworldcoder** [comment]
Possibly. I've was struggling trying to work out how best to trim the nodes so the visualisation makes sense to me. Right clicking and excluding was the natural way which worked great but when I shut the browser I lost where I was :)

Ok, I'll give the url idea a go

**Comment by yiquanzhou** [comment]
Ok, we will also see if we can save the recording filtering state automatically.

**Comment by yiquanzhou** [comment]
The filtering status of a recording is saved automatically from v20171115204348
