### ISSUE TITLE
Flow won't start on Ultimate 2017.1.5

### ISSUE THREAD

**Issue by alwyn** [findtheflow/Feedback#20]
Hi there,

The latest flow 6/24/2017 is unable to start on Intellij Idea ultimate 2017.1.5.

What is odd is that it does listen on at least one of the ports listed in the troubleshooting section, port 3571.

Is there a way that I can look at the error report sent in, maybe it will point out a local issue?

**Comment by yiquanzhou** [comment]
Hi @alwyn, you can check out the logs in ${User Directory}/.flow/logs to see if anything goes wrong on your machine. Please attach them here so we can help to find the issue.

**Comment by YoannBuch** [comment]
Fixed in version 20170718200811.
