### ISSUE TITLE
Tomcat not starting with Flow VM options

### ISSUE THREAD

**Issue by GuillaumeHaben** [findtheflow/Feedback#28]
Hi guys,

I tried to run Flow to record executions of my application. I'm working on Dspace with Tomcat 8. I downloaded the standalone version of Flow and I added those options to JAVA_OPTS in /etc/init/tomcat.conf: 
`-javaagent:/home/guillaume/.flow/resources/javaagent.jar -Dflow.agent.include=org.dspace`
After that, the tomcat service won't restart and the logs only say "java.lang.IllegalStateException: DSpace kernel cannot be null". 

I'm wondering if I need to add every single package of Dspace (I hope not, because I don't know how to find them all). Any ideas ?

**Comment by YoannBuch** [comment]
Hi Guillaume, 

You don't need to add every single package. Your configuration looks good.

I'll try to use Flow on DSpace and will let you know if I can figure this out.

In the meantime, can you confirm that you can record one of the JUnit tests? (do not forget the "-Dflow.agent.autostart" option to record from the beginning of the execution otherwise you won't see anything)

**Comment by GuillaumeHaben** [comment]
Hi Yoann,

I tried running the JUnit test case given in the Flow use cases. It worked well with IntelliJ's plugin.

A friend of mine tried to run Flow with a different installation of Tomcat (he installed it with the packet manager on his Ubuntu 16. I installed it manually because it wasn't available on Ubuntu 14) and it worked perfectly well. I guess that there is something wrong in my tomcat setup preventing Flow to work correctly. I'll keep you in touch if I find something...

**Comment by YoannBuch** [comment]
Sounds good!

Is there a version difference between your Tomcat and your friend's?
Did you both use the standalone version of Flow and the same way of adding the VM options?

**Comment by GuillaumeHaben** [comment]
My friend is running Tomcat 8.0.32 and I run Tomcat 8.5.23. We both use the standalone version of Flow and exactly the same VM options. Those options are set in a different file due to the difference of Tomcat versions but I know that VM options are processed: We tried to run VisualVM (which required other VM options) and it worked for both of us.

I'll try to switch to the same version of Tomcat to see if it works that way.

**Comment by YoannBuch** [comment]
Thank you, please let me know how it goes.

**Comment by GuillaumeHaben** [comment]
Just to give an update on this issue, I managed to make it work by installing Tomcat version 8.0.32. In my case Flow wasn't working with Tomcat 8.5.23. I let you decide if this information is enough to close the issue ;)

**Comment by YoannBuch** [comment]
Thanks for the update, Guillaume. Given our limited resources we're closing this issue for now.
