### ISSUE TITLE
Click to open in IDE shouldn't be the default action

### ISSUE THREAD

**Issue by alshain** [findtheflow/Feedback#36]
Bear in mind that I haven't used this for more than five minutes.

When exploring the data, just clicking on something shouldn't always send me to the IDE, it seems unnecessarily disruptive.

Also, double clicking something, i.e. to zoom in on a timeframe seems to send me to the IDE, I don't think this should happen. Sometimes the "zoom" by double click works, but right now, it always sends me to IntelliJ.

**Comment by YoannBuch** [comment]
Thanks for the feedback. I agree, it's not a good default behavior.  We may lose our focus in IntelliJ and we may end up with many tabs opened in IntelliJ while clicking around in Flow. 

We'll deactivate this behavior. The only way to select something in the IDE will be through the context menu.

**Comment by YoannBuch** [comment]
Clicking on a class/method/call no longer send me to the IDE.
Ctrl-click or the context menu must be used instead.

See https://plugins.jetbrains.com/plugin/8362-flow/update/44693
