### ISSUE TITLE
will provide a mvn jar to com.flow.agent.instrumentation.MethodInterceptor

### ISSUE THREAD

**Issue by leizhiyuan** [findtheflow/Feedback#9]
as I run

I have a project which I write a custom classloader to load my class file from pom file. If I only add java-agent,then I will get an error:

````
nested exception is java.lang.NoClassDefFoundError: com/flow/agent/instrumentation/MethodInterceptor
````
I tried to install the javaagent.jar to my m2 repository,like this
mvn install:install-file -Dfile=javaagent.jar -DgroupId=com.flow -DartifactId=com.flow.agent -Dversion=1.0.0.20170404 -Dpackaging=jar

but it seems not work.

so If you can provide a jar like ojdbc6.jar?

**Comment by YoannBuch** [comment]
I'm not sure to understand what you're trying to do. 

Have you tried to run your application with Flow from IntelliJ?

**Comment by leizhiyuan** [comment]
Thank you. @YoannBuch 
this problem occurs when I run in idea.
![image](https://cloud.githubusercontent.com/assets/2684384/24680948/7ed9ae36-19c5-11e7-9207-7dcfe9ae05a4.png)

although I add java-agent to my project, but my project use a custom container like tomcat. It will use a custom action to package the poject files, If I don't put a mvn jar to my pom.xml,It won't be packaged and loaded by the container.

as I know, flow agent will add proxy to all of classes, then It can  trace the call path, so during the startup of my project. I get the error.
<img width="1072" alt="problem" src="https://cloud.githubusercontent.com/assets/2684384/24681332/46044542-19c7-11e7-919f-c80486d660f5.png">

I think If I add the mvn jar to my pom.xml , It will work.

**Comment by leizhiyuan** [comment]
ok.I will try again. Thank you.
